development:
  adapter: postgresql
  database: spree_development_two_dot_two

test:
  adapter: postgresql
  database: spree_test_two_dot_two
  username: postgres
  min_messages: warning

production:
  adapter: postgresql
  database: spree_production_two_dot_two